var recipes = {
	chocolate_cake: {
		title: "Chocolate Cake",
		ingredients: [
			"flour",
			"milk",
			"chocolate",
			"2 cups white sugar",
			"1 3/4 cups all-purpose flour",
			"3/4 cup unsweetened cocoa powder",
			"1 1/2 teaspoons baking soda",
			"1 1/2 teaspoons baking powder",
			"1 teaspoon salt",
			"2 eggs",
			"1 cup milk",
			"1/2 cup vegetable oil",
			"2 teaspoons vanilla extract",
			"1 cup boiling water",
			"3/4 cup butter",
			"1 1/2 cups unsweetened cocoa powder",
			"5 1/3 cups confectioners' sugar",
			"2/3 cup milk",
			"1 teaspoon vanilla extract",



		],
		directions: [
			"preheat oven to 350 degrees F (175 degrees C). Grease and flour two 9 inch cake pans.",
			"Use the first set of ingredients to make the cake. In a medium bowl, stir together the sugar, flour, cocoa, baking soda, baking powder and salt. Add the eggs, milk, oil and vanilla, mix for 3 minutes with an electric mixer. Stir in the boiling water by hand. Pour evenly into the two prepared pans.",
			"Bake for 30 to 35 minutes in the preheated oven, until a toothpick inserted comes out clean. Cool for 10 minutes before removing from pans to cool completely.",
			"To make the frosting, use the second set of ingredients. Cream butter until light and fluffy. Stir in the cocoa and confectioners' sugar alternately with the milk and vanilla. Beat to a spreading consistency.",
			"Split the layers of cooled cake horizontally, cover the top of each layer with frosting, then stack them onto a serving plate. Frost the outside of the cake.",
			"*Tip: Aluminum foil can be used to keep food moist, cook it evenly, and make clean-up easier.",
		],
		image: "http://www.chowstatic.com/blog-media/2015/01/1.jpg",
	},
	waffle: {
		title: "Waffle Recipe",
		ingredients: [
			"6 tablespoons unsalted butter",
			"2 1/2 cups Gold Medal whole wheat flour",
			"1/3 cup packed light brown sugar",
			"2 1/4 teaspoons baking powder",
			"1 teaspoon baking soda",
			"1/2 teaspoon salt",
			"2 teaspoons ground cinnamon",
			"1/2 teaspoon ground ginger",
			"1/4 teaspoon ground nutmeg",
			"1/4 teaspoon ground cloves",
			"4 large eggs, beaten",
			"2 cups buttermilk",
			"1 teaspoon vanilla extract",
			"1 cup canned solid-pack pumpkin",
			"Brown Butter Buttermilk Syrup, for serving",
		],
		directions: [
			"Preheat waffle iron. In a small saucepan, melt the butter over medium-low heat and continue to cook, swirling occasionally, until butter turns golden brown, Skim foam from top, and remove from heat. Pour into a bowl to stop the cooking, leaving any burned sediment behind; let cool.",
			"In a medium bowl, whisk together flour, brown sugar, baking powder, soda, salt, and spices.",
			"In a large bowl, whisk together eggs, buttermilk, vanilla, pumpkin, and browned butter. Whisk in dry ingredients just until smooth.",
			"Spray hot waffle iron with cooking spray and spoon batter into waffle iron, spreading quickly. Cook according to manufacturer’s instructions. Continue making waffles until batter is gone. Keep waffles warm in a 250 degree F oven. Serve warm with Brown Butter Buttermilk Syrup, if desired.",
			"* Note: These waffles freeze well. Cool completely and put in a freezer bag! Pop them in the toaster to reheat!",
			
		],
		image: "http://www.twopeasandtheirpod.com/wp-content/uploads/2013/09/Brown-Butter-Pumpkin-Waffles-4.jpg",
	},
	bread: {
		title: "Bread Recipe",
		ingredients: [
			"1 1/8 cups water",
			"3 cups whole wheat flour",
			"1 1/2 teaspoons salt",
			"1/3 cup honey",
			"1 tablespoon dry milk powder",
			"1 1/2 tablespoons shortening",
			"1 1/2 teaspoons active dry yeast",
		],
		directions: [
			"Place ingredients in bread machine pan in the order suggested by the manufacturer. Select Whole Wheat setting, and then press Start.",
			"Cook for 3 hours",
		],
		image: "https://upload.wikimedia.org/wikipedia/commons/7/71/Anadama_bread_(1).jpg",
	},
	sushi: {
		title: "Sushi Recipe",
		ingredients: [
			"2/3 cup uncooked short-grain white rice",
			"3 tablespoons rice vinegar",
			"3 tablespoons white sugar",
			"1 1/2 teaspoons salt",
			"4 sheets nori seaweed sheets",
			"1/2 cucumber, peeled, cut into small strips",
			"2 tablespoons pickled ginger",
			"1 avocado",
			"1/2 pound imitation crabmeat, flaked",
		],
		directions: [
			"In a medium saucepan, bring 1 1/3 cups water to a boil. Add rice, and stir. Reduce heat, cover, and simmer for 20 minutes. In a small bowl, mix the rice vinegar, sugar ,and salt. Blend the mixture into the rice.",
			"Preheat oven to 300 degrees F (150 degrees C). On a medium baking sheet, heat nori in the preheated oven 1 to 2 minutes, until warm.",
			"Center one sheet nori on a bamboo sushi mat. Wet your hands. Using your hands, spread a thin layer of rice on the sheet of nori, and press into a thin layer. Arrange 1/4 of the cucumber, ginger, avocado, and imitation crabmeat in a line down the center of the rice. Lift the end of the mat, and gently roll it over the ingredients, pressing gently. Roll it forward to make a complete roll. Repeat with remaining ingredients.",
			"Cut each roll into 4 to 6 slices using a wet, sharp knife.",
			"*Tip 1: If you do not have a bamboo sushi mat, the easiest way to roll the sushi is to use a clean dish towel.",
			"**Tip 2: Aluminum foil can be used to keep food moist, cook it evenly, and make clean-up easier.",
		],
		image: "http://www.house-sushi.com/wp-content/uploads/2013/12/sushi.jpg",
	},
	pizza: {
		title: "Pizza Recipe",
		ingredients: [
			"3 1/2 cups all-purpose flour",
			"1 teaspoon salt",
			"1 cup water",
			"1 (.25 ounce) package active dry yeast",
			"1 pinch white sugar",
			"1/4 cup flour for dusting",
			"2 cups pizza sauce",
			"20 slices fresh mozzarella cheese",
			"20 leaves fresh basil",
			"olive oil",
			"sea salt to taste",
		],
		directions: [
			"Stir flour and 1 teaspoon salt in a bowl. Set aside.",
			"Mix water, yeast, and sugar in a large bowl. Let stand until yeast begins to form a creamy foam, about 5 minutes.",
			"Stir half the flour mixture into yeast mixture until no dry spots remain. Stir in remaining flour, 1/2 cup at a time, mixing well after each addition. When dough pulls together, turn it out onto a lightly floured surface and knead until smooth and elastic, about 8 minutes.",
			"Lightly oil a large bowl, then place dough in the bowl and turn to coat with oil. Cover with a light cloth and let rise in a warm place (80 to 95 degrees F (27 to 35 degrees C)) until doubled in volume, about 1 hour. Punch dough down, divide into 4 equal pieces, and form each into a ball.",
			"Preheat oven with a pizza stone to 500 degrees F (260 degrees C).",
			"Stretch out and pat 1 dough ball to form a circle 10 to 12 inches in diameter. Place dough on a lightly floured pizza peel. Top with 1/2 cup of tomato sauce and spread to cover within an inch of the edge of the dough. Arrange 5 slices of mozzarella cheese on top of the tomato sauce, then place 5 basil leaves on top. Drizzle pizza with 1 tablespoon olive oil and sprinkle with sea salt to taste. Repeat for 3 remaining dough balls.",
			"Slide each pizza onto the pizza stone in the preheated oven. Bake until cheese is bubbly and the underside of the crust is golden brown, 5 to 7 minutes.",
		],
		image: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg",
	},
	salad: {
		title: "Salad Recipe",
		ingredients: [
			"1/2 cup finely chopped red onions",
			"1/4 cup water",
			"1/2 cup red wine vinegar",
			"2 teaspoons kosher salt, plus additional as needed",
			"2 teaspoons coarsely ground fresh black pepper, plus additional as needed",
			"1/2 to 1 cup extra virgin olive oil",
			"1 large head iceburg lettuce, cut into 1/2-inch pieces, 6 to 8 cups",
			"1 cup Roasted Marinated Peppers , cut into 1/2-inch pieces",
			"1 cup Roasted Marinated Peppers , cut into 1/2-inch pieces",
			"1/2 cup pitted black olives, such as Cerignola, halved",
			"1 cup haricots verts, cut into 1-inch pieces",
			"1 cup English cucumber, peeled and cut into 1/2-inch pieces",
			"2 tablespoons fresh marjoram leaves",
			"1/4 cup flat-leaf parsley leaves",
			"1/4 cup coarsely chopped dill, large stems removed",
		],
		directions: [
			" In a small bowl, combine the onions, water, vinegar, salt, and pepper. Let sit at room temperature for 5 minutes to allow the flavors to develop.",
			"Add 1/2 cup of the oil to the vinegar mixture. Add additional to taste.",
			"In a large bowl, combine the lettuce, roasted peppers, olives, haricots verts, cucumber, and herbs. Toss with enough dressing to coat, and season to taste with additional salt and pepper. Serve any remaining dressing on the side.",
		],
		image: "http://www.cornerbakerycafe.com/getmedia/63a151e3-77d3-4fd4-9d86-624f7616e9c0/Chopped-Salad_550x310?width=550&height=310&ext=.jpg",
	},
	pasta: {
		title: "Pasta Recipe",
		ingredients: [
			"2 cups dried Chinese egg noodles or fine egg noodles (4 ounces)",
			"1/4 teaspoon ground ginger",
			"1/3 cup bottled stir-fry sauce",
			"1 cup snow pea pods or fresh sugar",
			"snap peas, tips and stems removed, and cut up",
			"1 medium red sweet pepper, cut into bite-size strips",
			"2 teaspoons peanut oil or cooking oil",
			"5 ounces cooked chicken breast, cut into strips (about 1 cup)",
			"2 tablespoons coarsely chopped cashews or peanuts or toasted sliced almonds",
		],
		directions: [
			"Cook noodles according to package directions. Drain; set aside. Stir ginger into the bottled stir-fry sauce; set aside.",
			"In a large skillet cook and stir peas and sweet pepper in hot oil over medium-high heat for 3 to 5 minutes or until crisp-tender. Add cooked noodles, chicken, stir-fry sauce, and cashews; heat through.",
		],
		image: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Asian_Style_Italian_Pasta.jpg",
	},
	jam: {
		title: "Blackberry Jam Recipe",
		ingredients: [
			"4 cups blackberries",
			"1 cup white sugar",
			"2 tablespoons cornstarch",
			"1/4 teaspoon ground cinnamon",
			"1/4 teaspoon ground allspice",
			"1/2 teaspoon lemon juice",
		],
		directions: [
			"Mash blackberries in a saucepan with a potato masher. Stir in sugar until juices form; place about 1 tablespoon blackberry juice in a small bowl and stir in cornstarch. Pour cornstarch mixture into saucepan.",
			"Bring berries to a boil, stirring often, until jam is thickened, about 15 minutes. Stir in cinnamon and allspice. Remove from heat and allow to cool. Transfer jam to a bowl, cover, and refrigerate until chilled. Stir in lemon juice.",
		],
		image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTrT0STGzHVV798xljoRlVTzcZPqg1jiAk96BCt-H1JNlg1hSY",
	},
	pizza_dough: {
		title: "Pizza Dough Recipe",
		ingredients: [
			"1c hot water",        
			"1 tbl yeast",
			"2 tsp sugar",
			"1 tsp salt",
			"2 tbl olive oil",
			"2.5 c flour",
		],
		directions: [
			"Mix yeast, water, and sugar. Let stand.",
			"In mixing bowl, mix flour, oil, and salt.",
			"Once yeast mixture has risen, mix all ingredients.",
			"Let dough rest in bowl covered with a towel in a warm place for 30 minutes.",
			"oll out dough and add sauce and toppings. Bake at 400 F  for 20 minutes.",
		],
		image: "http://foodnetwork.sndimg.com/content/dam/images/food/fullset/2011/7/26/2/GT0303_pizza-dough_s4x3.jpg",
	},

};